### ISSUE TITLE
Some of the columns from the groups table must not be sortable

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-splunk#1179]
| Wazuh | Splunk | Rev  |
| ----- | -------| ---  |
| 4.x   | 8.x.x  | 4206 |

**Description**
The columns `Agents` and `Checksum` are not sortable. Sorting them launches a request that causes a 400 response from the Wazuh API.

**Steps to reproduce**

1. Go to the Management > Groups section.
2. Scroll down to the table and sort any of these 2 columns.
3. Check how it produces an error:
 - Table stuck on loading state.
 - Error in promise (see below).
 - Error in the backend and on the Wazuh API (see the logs, below).

```js
sort.js:40 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'message')
    at sort
```

**Screenshots**
![image](https://user-images.githubusercontent.com/15186973/145420984-2a3cfd4d-4c59-4bd4-a4b3-5b975be1b5a9.png)

**Additional context**
API response catched on the app's backend logs.

`docker-compose exec -u root indexer tail -f /opt/splunk/var/log/splunk/SplunkAppForWazuh.log`

```python
ERROR: 2021/12/09 11:56:15: 'Wazuh_API: {'title': 'Bad Request', 'detail': "Not a valid sort field : Allowerd sort fields: ['name']. Fields: mergedSum", 'remediation': 'Please, use only allowed sort fields', 'dapi_errors': {'master-node': {'error': "Not a valid sort field : Allowerd sort fields: ['name']. Fields: mergedSum"}}, 'error': 1403}'
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/wazuh_api.py", line 149, in make_request
    response = catch_exceptions(response)
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/wazuh_api.py", line 99, in catch_exceptions
    raise e
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/wazuh_api.py", line 94, in catch_exceptions
    raise Exception(response.json())
Exception: {'title': 'Bad Request', 'detail': "Not a valid sort field : Allowerd sort fields: ['name']. Fields: mergedSum", 'remediation': 'Please, use only allowed sort fields', 'dapi_errors': {'master-node': {'error': "Not a valid sort field : Allowerd sort fields: ['name']. Fields: mergedSum"}}, 'error': 1403}
ERROR: 2021/12/09 11:56:15: 'api: Error making API request: {'title': 'Bad Request', 'detail': "Not a valid sort field : Allowerd sort fields: ['name']. Fields: mergedSum", 'remediation': 'Please, use only allowed sort fields', 'dapi_errors': {'master-node': {'error': "Not a valid sort field : Allowerd sort fields: ['name']. Fields: mergedSum"}}, 'error': 1403}'
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/appserver/controllers/api.py", line 151, in request
    current_api=current_api_json
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/wazuh_api.py", line 273, in make_request
    raise e
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/wazuh_api.py", line 149, in make_request
    response = catch_exceptions(response)
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/wazuh_api.py", line 99, in catch_exceptions
    raise e
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/wazuh_api.py", line 94, in catch_exceptions
    raise Exception(response.json())
Exception: {'title': 'Bad Request', 'detail': "Not a valid sort field : Allowerd sort fields: ['name']. Fields: mergedSum", 'remediation': 'Please, use only allowed sort fields', 'dapi_errors': {'master-node': {'error': "Not a valid sort field : Allowerd sort fields: ['name']. Fields: mergedSum"}}, 'error': 1403}
```

**Comment by AlexRuiz7** [comment]
![image](https://user-images.githubusercontent.com/15186973/147831605-aeacae27-8a05-4201-9912-007f906444e0.png)
