### ISSUE TITLE
Reporting fails when getting out of the controller

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-splunk#486]
Hi team, it's been reported that the `Reporting` feature stops working when getting out of the current controller to another one while a report is being generated.

```
 FPDF error: Not a PNG file: /opt/splunk/etc/apps/SplunkAppForWazuh/appserver/static/top5AgentsVizz.png" }
Traceback (most recent call last):
  File "<string>", line 211, in generate
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/fpdf/fpdf.py", line 167, in wrapper
    return fn(self, *args, **kwargs)
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/fpdf/fpdf.py", line 1004, in image
    info=self._parsepng(name)
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/fpdf/fpdf.py", line 1851, in _parsepng
    self.error('Not a PNG file: ' + filename)
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/fpdf/fpdf.py", line 251, in error
    raise RuntimeError('FPDF error: '+msg)
RuntimeError: FPDF error: Not a PNG file: /opt/splunk/etc/apps/SplunkAppForWazuh/appserver/static/top5AgentsVizz.png
```

Cheers

**Comment by adri9valle** [comment]
Solved => https://github.com/wazuh/wazuh-splunk/pull/498
